kind: Service
apiVersion: v1
metadata:
  name: lbg-api-app
spec:
  type: LoadBalancer
  selector:
    app: lbg-api-app
  ports:
  - protocol: TCP
    port: 80        # Defines the Service's port within the cluster
    targetPort: 4000  # Defines the Pod's port
